name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Trigger deployment
      run: |
        response=$(curl -s -X POST "${{ secrets.RENDER_DEPLOY_URL }}")
        echo "Deployment response: $response"
        
        if echo "$response" | jq -e '.deploy.id' > /dev/null; then
          deploy_id=$(echo "$response" | jq -r '.deploy.id')
          echo "Deployment triggered successfully with ID: $deploy_id"
        else
          echo "Deployment failed - no deploy ID found in response"
          exit 1
        fi
